### ISSUE TITLE
MD5 export?

### ISSUE THREAD

**Issue by orange451** [zturtleman/mm3d#111]
Hiah! I remember seeing a post you made on the quake forums saying you added MD5 exporting ability to your version of MM3D. I was wondering if that could be made public. I'd really like to convert some models to MD5 format!

**Comment by zturtleman** [comment]
I added exporting SMD, IQE, and incomplete non-public IQM but I haven't worked on MD5. There is a [Misfit Cubed](https://sourceforge.net/projects/misfitcubed/) project that has MD5 export. A new MD5 exporter based on my IQE exporter is planned to be added to Maverick eventually.

**Comment by orange451** [comment]
Oh my apologies, I must have misread this forum post: https://discourse.ioquake.org/t/current-status-of-iqm-md5-models/1153/3

Thanks for the info!

**Comment by zturtleman** [comment]
Closing as duplicate of #36.
