### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by alexmyczko** [zturtleman/mm3d#13]
Hi

Do you plan to integrate the 3 available plugins? http://www.misfitcode.com/misfitmodel3d/plugins.html

Trying to build them, i was only able to build 1/3.

**Comment by zturtleman** [comment]
No, I wasn't planning to.

ACTC plugin is under a license incompatible with the GPL. It uses internal MM3D classes so using the plugin is probably a GPL violation. I don't think I can ship it with mm3d binary releases.

ImLib2 plugin which allows loading .GIF, .PNM, .TIF/.TIFF isn't needed anymore. Qt5 has [builtin support](https://doc.qt.io/qt-5.10/qimage.html#reading-and-writing-image-files) for .GIF and pnm formats (.PGM, .PBM, .PPM). [Qt5 image format plugins](https://doc.qt.io/qt-5.10/qtimageformats-index.html) adds .TIF/.TIFF (optionally provided by Debian `qt5-image-formats-plugins` package).

I don't really have a reason against the .3ds importer. Though I don't really see value in having it so I don't want to work on integrating or improving it.
