### ISSUE TITLE
Save animation.cfg checkbox reset

### ISSUE THREAD

**Issue by quakemmo** [zturtleman/mm3d#156]
It would be nice if that checkbox wasn't prechecked everytime, but kept state from previous save.

As it is, if I'm working on a model where I don't want to save animation.cfg, I have to uncheck this every time I save, and I inevitably forget to do it once and then have to say bad words out loud about myself.

**Comment by zturtleman** [comment]
The state is now stored in meta-data as MD3_animationcfg 0 or 1. 0836e127732cf1a19abae79f7b3f2728c5b7f288.
