### ISSUE TITLE
Obj won't load in non-english locales (if locale has comma as decimal separator)

### ISSUE THREAD

**Issue by dvhx** [zturtleman/mm3d#159]
This works fine:

    LANG=en_US mm3d cube.obj

This does not:

    LANG=sk_SK mm3d cube.obj

Because slovak numbers use comma instead of dot. mm3d should ignore locale format for numbers and use dot every time, because OBJ format always uses dots as decimal separators.

**Comment by zturtleman** [comment]
Fixed in f00fdd5f2a27292a646a23ba34f80be50ab9844c. Thanks.
