### ISSUE TITLE
configure fails on Arch Linux

### ISSUE THREAD

**Issue by zturtleman** [zturtleman/mm3d#161]
_Originally posted by @InFerYes in https://github.com/zturtleman/mm3d/issues/44#issuecomment-891216578_

I have this error on Arch Linux.

```
checking for OpenGL... yes
checking for Qt... no
checking Qt OpenGL... failure
configure: error: Failed to link Qt with OpenGL support.

```
When I use `./configure --with-Qt-include-dir=/usr/lib64` I get 
```
checking for Qt... yes:
    QT_CXXFLAGS=-I/usr/lib64
    QT_DIR=/usr
    QT_LIBS=-L/usr/lib64 -lQt5Core -lQt5Gui -lQt5Widgets -lQt5OpenGL
    QT_UIC=/usr/bin/uic
    QT_MOC=/usr/bin/moc
    QT_RCC=/usr/bin/rcc
    QT_LRELEASE=/usr/bin/lrelease
    QT_MACDEPLOYQT=
checking correct functioning of Qt installation... cat: bnv_qt_test.cpp: No such file or directory
failure
configure: error: Failed to find matching components of a complete
                  Qt installation. Try using more options,
                  see ./configure --help.
```
```
% qmake-qt5 --version
QMake version 3.1
Using Qt version 5.15.2 in /usr/lib
```

How to proceed?

**Comment by zturtleman** [comment]
I have no idea about the message `cat: bnv_qt_test.cpp: No such file or directory`. Though `-lQt5OpenGL` shows this is older Maverick code.

I installed Arch Linux and fixed detecting the include path for Qt in configure. It builds and runs for me.

Try installing Arch Linux build dependencies (now listed in the README file)

```
sudo pacman -S autoconf automake make gcc qt5-base qt5-tools glu
```

and set the correct Qt include directory.

```
./configure --with-Qt-include-dir=/usr/include/qt
```

If this still fails, trying using the latest source code with just plain `./configure`.

```
sudo pacman -S git
git clone http://github.com/zturtleman/mm3d.git ~/mm3d
cd ~/mm3d
./autogen.sh
./configure
make
sudo make install
```

**Comment by InFerYes** [comment]
I already have these packages installed:

```
warning: autoconf-2.71-1 is up to date -- reinstalling
warning: automake-1.16.3-1 is up to date -- reinstalling
warning: make-4.3-3 is up to date -- reinstalling
warning: gcc-11.1.0-1 is up to date -- reinstalling
warning: qt5-base-5.15.2+kde+r210-1 is up to date -- reinstalling
warning: qt5-tools-5.15.2+kde+r17-3 is up to date -- reinstalling
warning: glu-9.0.2-1 is up to date -- reinstalling
```
Using `./configure --with-Qt-include-dir=/usr/include/qt` did the trick for me!

![image](https://user-images.githubusercontent.com/8770637/127988122-60ef61ae-bbd0-4c77-8c59-298985123d49.png)

Many thanks for the swift resolution.

**Comment by zturtleman** [comment]
You're welcome.
