### ISSUE TITLE
Split Animation not working as intended?

### ISSUE THREAD

**Issue by frozenMeatpopsicle** [zturtleman/mm3d#162]
The help dialog for Animation Sets says that:

> The Split button will split a selected animation into two separate animations at the frame you specify. The specified frame and all successive frames will be removed from the original animation. The new animation will begin with the specified frame and contain all successive frames.

So if I'm reading correctly, if I specify frame 2 of a 10 frame animation, the original set should now contain a single frame, and the new set should contain 9 frames, starting from the frame 2 of the original set?

That is not currently the case. Currently it splits from the frame after the one specified. Using the same example; when I specify frame 2 of a 10 frame animation, the original set is now 2 frames long, and the new set now contains 8 frames, starting from the frame 3 of the original set.

Using Linux build, app version 1.3.12

**Comment by zturtleman** [comment]
Thanks. Fixed in 1f2bf22855f25ecb2bef791e1d18131c6f47c9c2 so that the behavior now matches the documentation.
