### ISSUE TITLE
md3filter.cc DBL_MIN should probably be -DBL_MAX

### ISSUE THREAD

**Issue by mick-p1982** [zturtleman/mm3d#175]
[            double dmax[4] = { DBL_MIN, DBL_MIN, DBL_MIN, 1 };](https://github.com/zturtleman/mm3d/blob/53b0d1b33412bddacd65559f41d5511b9050a27a/src/libmm3d/md3filter.cc#L2085)

I was just checking for this common mistake (owing to C stupidity in defining INT_MIN and FLT_MIN/DBL_MIN.)

**Comment by zturtleman** [comment]
Fixed in 8d15ec889da1f5fd7fe2a25c0c4ad34a06526bfb. Thanks.
