### ISSUE TITLE
edgedivcmd.cc reverses addTriangleToGroup's args

### ISSUE THREAD

**Issue by mick-p1982** [zturtleman/mm3d#178]
https://github.com/zturtleman/mm3d/blob/53b0d1b33412bddacd65559f41d5511b9050a27a/src/commands/edgedivcmd.cc#L109-L112

Unrelated: Below is some code for adding texture coordinates to this command..

```
				float st[2][3],dst[2][3]; 				
				model->getTextureCoords(tri,st); //2022									
				
				for(int i=2;i-->0;)
				{
					dst[i][a] = (st[i][a]+st[i][b])*0.5f;
					dst[i][b] = st[i][b];
					dst[i][c] = st[i][c];
				}
				model->setTextureCoords(newTri,dst);

				for(int i=2;i-->0;)
				{
					dst[i][a] = st[i][a];
					dst[i][b] = (st[i][a]+st[i][b])*0.5f;
					dst[i][c] = st[i][c];
				}
				model->setTextureCoords(tri,dst);
```

**Comment by zturtleman** [comment]
Fixed Edge Divide group in 74377bbfae114da6c10e5648031fed98a206043b and texture coords in df58eb9585a1c7322ce2ab6e9309d61e484c3512. Thanks.
