### ISSUE TITLE
After creating triangle using "Make face from vertices", allow "Invert normals" to operate on this newly added triangle

### ISSUE THREAD

**Issue by dvhx** [zturtleman/mm3d#185]
I select 3 points, then press "k" to "Make face from vertices", good. I select another 3 vertices and press "k" to "Make face from vertices" but because I chose points in slightly different order, the triangle is facing away from me. There is "Invert normals" command but it only works on selected faces. If I press "I" just after I create new triangle, make it invert normal of this newly created triangle. Or add some other tool that would allow me to invert face of recently added triangle.

- I cannot select points in correct order because selecting points is already difficult in complex geometries
- I cannot select newly created face because I would loose vertices selection and I usually want to create more than 1 triangle

I want it to work like this:
1. I select 3 points
3. "k" to "Make face from vertices"
4. "i" to "Invert normals" if new triangle is facing wrong way
5. Right mouse to de-select points I don't need
6. Left mouse button to select new points to have 3 points in selection
8. goto 3

If it is not possible you can make "Invert normals or recently created triangle" and I will bind a "j" to it or whatever.

**Comment by mick-p1982** [comment]
I think you want to auto-select the new face. I think that is best too. But I checked my fork (https://github.com/mick-p1982/mm3d) and it doesn't that, so I will try to remember to add this. Anyway, you might want to try my fork since it's a lot better. But it's not back-compatible. Also the default hotkeys are different.

**Comment by zturtleman** [comment]
The created triangle is now auto-selected (ed316269dc1a43fb88520b522eb166e1e8b25b1f) and the Select Vertex tool will (un)select triangles (fd1165f491e6e1738a07a63c9416879929a39d36). The process @dvhx wrote should work now.
