### ISSUE TITLE
Support holding shift in texture coordinate editor

### ISSUE THREAD

**Issue by Enjay001** [zturtleman/mm3d#25]
One of the things that has always bothered me in Misfit is that there is no way to restrict the moment of vertices to a single plane in the texture coordinate editor.

In the main 3D editing screens, if you hold shift in move mode and then start moving a vertex (or whatever) then Misfit (now Maverick) will restrict movement to whichever direction (X, Y or Z) you start moving in; thereby ensuring (for example) a point being moved horizontally stays at exactly the same height as it was.

Unless I'm doing it wrong, there doesn't seem to be an equivalent functionality in the texture coordinate editor.  So moving a point (or group of points) in the Y axis means that you need a very steady hand to avoid shifting them in the X axis a little bit too.

If some way (probably using shift, like in the 3D editor) to clamp movement to the X or Y direction in the texture editor could be added, it would be greatly appreciated.  Thank you.

**Comment by zturtleman** [comment]
Sounds like a good idea.

**Comment by zturtleman** [comment]
Added shift support for move, rotate, and scale in texture coordinate editor in https://github.com/zturtleman/mm3d/commit/99df34f35a486a2e7e5f56638e93a770acc06e7a. (It was already supported for select.)
