### ISSUE TITLE
Paint Texture creates a black PNG

### ISSUE THREAD

**Issue by Enjay001** [zturtleman/mm3d#26]
I tried the Paint Texture feature and althouth it looks good in Maverick, the image saved was totally black.  I tried all combinations of fill, edges and vertices but all just saved as totally black images.

How it looked in Maverick
![paintt1](https://user-images.githubusercontent.com/24989228/47606332-3cd63700-da0a-11e8-8045-257283c78e4c.png)

What was saved
![black01](https://user-images.githubusercontent.com/24989228/47606331-3cd63700-da0a-11e8-9914-ad9f2a4245ef.png)

**Comment by zturtleman** [comment]
Fixed in https://github.com/zturtleman/mm3d/commit/aa824535f69f18de85ce4a37d500be6247919c56, thanks.

**Comment by Enjay001** [comment]
Thank you.  Confirmed as working in the build you posted in the other issue thread.
