### ISSUE TITLE
Texture Coordinate Editor (etc) Can't see the texture initially.

### ISSUE THREAD

**Issue by Enjay001** [zturtleman/mm3d#27]
Loading a model that already has a skin allocated and then trying to do something with that skin hits a minor hiccup.  Even though the 3D preview in the main screen shows the model textured, the materials dialogue and the texture coordinate editor just show a white image.

To fix this, all I have to do is use the drop down menu in the materials dialogue and select the skin again (even it is was already selected) then it works.  This wasn't necessary with Misfit.

The following pic are taken when editing a simple MD3 with only one skin image (I noticed the same thing happening with other file formats).

Texture coordinate editor showing white skin image
![001](https://user-images.githubusercontent.com/24989228/47606412-43b17980-da0b-11e8-9590-ac0b1d9c47bb.png)

Materials editor showing that the skin (PChest.png) is slected - but showing as totally white
![002](https://user-images.githubusercontent.com/24989228/47606413-43b17980-da0b-11e8-8a17-fee0f9c9bc5f.png)

Reselecting it from the drop down makes it appear
![003](https://user-images.githubusercontent.com/24989228/47606414-43b17980-da0b-11e8-82fc-b0c15592e957.png)

And now it can be seen in the texture coordinate editor too.
![004](https://user-images.githubusercontent.com/24989228/47606415-43b17980-da0b-11e8-9274-a8c8ef6468aa.png)

**Comment by zturtleman** [comment]
Fixed in https://github.com/zturtleman/mm3d/commit/12c4b1d2da288a2220b2b8b09968fe52eed15dfd, thanks.

Update for Maverick Model 3D 1.3.10, extract in `C:\Program Files (x86)\Maverick Model 3D\`, or where ever you installed it: [maverickmodel3d-1.3.10-20181027-aa824535.zip](https://github.com/zturtleman/mm3d/files/2522454/maverickmodel3d-1.3.10-20181027-aa824535.zip)

**Comment by Enjay001** [comment]
That has indeed fixed it.  Thank you very much. :)
