### ISSUE TITLE
RgbaWin probably unused; instance constructed on stack in texwin.cc

### ISSUE THREAD

**Issue by mick-p1982** [zturtleman/mm3d#45]
https://github.com/zturtleman/mm3d/blob/0f4170788af8f19f8331ae87d515173b71763c27/src/implui/texwin.cc#L467

FWIW I was looking at the `emit` cases, and one was not attached with `connect` anywhere (`valuesChanged`) so I looked for instances of the class. And just found the one in the link, that looks erroneous.

The HTML doc for RgbaWin is removed now, but was once in package lists.

**Comment by zturtleman** [comment]
Removed RgbaWin in 2a378f673739380ee19360f4b56e26660679d420, thanks.
