### ISSUE TITLE
Oversights: Influences->Edit Joints 

### ISSUE THREAD

**Issue by mick-p1982** [zturtleman/mm3d#49]
I think the Delete button in jointwin.h/cc should reset the selection menu, or else it will be unusable/retain the deleted joint. 

It also has problems when there are not joints in the model. Maybe the menu item should be disabled in that case.

**Comment by zturtleman** [comment]
Yeah, the delete joint button doesn't seem to work and list should probably default to "No joints" or something and not be selectable.

**Comment by zturtleman** [comment]
Fixed in https://github.com/zturtleman/mm3d/commit/d1b429433394488ba4f7c04d9cb26fa36c9635dc. Thanks.
