### ISSUE TITLE
md3filter.cc code broken, weirdly

### ISSUE THREAD

**Issue by mick-p1982** [zturtleman/mm3d#74]
https://github.com/zturtleman/mm3d/blob/1282798bbef7a72896cf0d1beff82c8f0b7eff8f/src/libmm3d/md3filter.cc#L1023

Any idea what's up here? meshTriangleCount is not a compile-time constant value.

**Comment by zturtleman** [comment]
It's a [variable-length array](https://en.wikipedia.org/wiki/Variable-length_array). It can be changed to a std::vector or whatever.

**Comment by mick-p1982** [comment]
Thanks, never seen this before. I guess it's new to C99. I don't C++ is a strict superset of C99 extensions.

https://stackoverflow.com/questions/1887097/why-arent-variable-length-arrays-part-of-the-c-standard

**Comment by zturtleman** [comment]
Fixed in 167792432eca5bcc52987f08132e88a0d1ef11d7.

**Comment by mick-p1982** [comment]
Off-topic: I didn't realize C++11 enables a vector of C-array type. It seems like it can't do a lot... not even resize. Always cool to learn something new that isn't an outlandish feature.
