### ISSUE TITLE
SMD export doesn't seem to export animations properly

### ISSUE THREAD

**Issue by orange451** [zturtleman/mm3d#76]
I use ASSIMP for model loading in my engine. I've loaded a few SMD animations that I decompiled from their respective MDL models, and they load fine in my engine. When I load a SMD generated from misfit, my models are missing both animations and keyframes.

Upon import: Only 1 animation is created and that animation contains only 1 keyframe.

**Comment by zturtleman** [comment]
A SMD file only contains meshes and bind pose or a single animation. The model and each animation has to be manually exported to a separate file from Maverick (model.smd, anim1.smd, anim2.smd, ...).

**Comment by orange451** [comment]
Oh my apologies for the misunderstanding. How do I export each separate animation from Maverick?

**Comment by zturtleman** [comment]
Currently each animation has to be saved separate from File -> Export -> Choose filename with .smd extension. Export a "Reference" model type for meshes / skeleton and then export again with "Animation" model type for each animation. Batch export is missing; partially because the filename has to be chosen before what to export.

**Comment by orange451** [comment]
Perhaps for the batch export, the user defines the name for just the reference model, then Maverick will create an additional folder of the same name, and export each animation (using the name of the animation as the filename). This is how MDL decompiling tools (such as crowbar) work.

**Comment by orange451** [comment]
Also, thanks for creating SMD export. I was able to get it to load into my engine:
https://i.imgur.com/0llCfYk.gif

There's no animation smoothing yet.
