### ISSUE TITLE
Qt5 support?

### ISSUE THREAD

**Issue by alexmyczko** [zturtleman/mm3d#8]
Is there plans for a qt5 update?

https://wiki.qt.io/Transition_from_Qt_4.x_to_Qt5

**Comment by zturtleman** [comment]
Switching to Qt 5 was easier than I expected. 84e32d74f3d25d7c759d3de9be61119c70e150db

**Comment by alexmyczko** [comment]
I keep getting ./configure error like
checking Qt OpenGL... failure

what could I be missing? when you say it worked for you on your debian, which pkgs did you install (the qt and -dev ones)

**Comment by alexmyczko** [comment]
no worries, i got it to build :)
